apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-affinity
  namespace: osfp
  labels:
   app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - small


# First assign labels on all nodes in our cluster
# kubectl label nodes node-1 size=small
# kubectl label nodes node-2 size=large
#
# Confirm the labels
# kubectl get nodes --show-labels
#
#
#
# kubectl apply -f 05-pod-with-node-affinity.yml
# kubectl -n osfp get no -o wide
