apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-affinity-cannot
  namespace: osfp
  labels:
   app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: NotIn
            values:
            - small
            


#
# Lets think we have some nodes with label small/medium/large
# We want this pod, NEVER to be deployed on node having size=small
