apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
   app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx



# kubectl apply -f 01-simple-pod.yml
# kubectl get po
#
