apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-container
    image: mysql:latest
    ports:
    - containerPort: 3329
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "osfp@321"


# kubectl apply -f 03-pod-with-env-variable.yml
# kubectl get po
# kubectl exec -it mysql-pod -- bash
# mysql -u root -p
# SHOW DATABASES;
# exit
