apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: osfp
  labels:
   app: ubuntu
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"


# Pod will start with 0.5 CPU sahre and can go up to 1 CPU
# kubectl apply -f 04-pod-with-cpu-limit.yml
# kubectl -n osfp get po
# kubectl -n osfp describe pod ubuntu-pod
