apiVersion: v1

kind: Pod

metadata:
  name: nginx-pod

spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        requests: #request means minimum
          cpu: "500m"
          memory: "128Mi"
        limits: #limits means maximum
          cpu: "1000m"
          memory: "256Mi"
