apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploymnet
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
#uncomment below two lines when you update to a new image
#      annotations:
#        kubernetes.io/change-cause: "updated to new version"
      labels:
        app: nginx
    spec:
      affinity:
        podAffinity:
        #podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
               matchLabels:
                  app: nginx
      containers:
        - name: nginx-container
#for checking rolling updates first try with
#         image: nginx
#create deployment and check it, then change
#         image: nginx:1.27
          image: nginx
          livenessProbe:
            exec:
              command:
              - cat
              - /usr/share/nginx/index.html
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 20
            failureThreshold: 3
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
